import os
import json
import time
import firebase_admin
from firebase_admin import credentials, db
from natsort import natsorted
from rich.console import Console
from rich.table import Table
from rich.panel import Panel
from rich.live import Live
from rich.tree import Tree

console = Console()

# --- FIREBASE SETUP ---
if not firebase_admin._apps:
    try:
        key_json = os.environ.get("FIREBASE_SERVICE_KEY")
        if key_json:
            cred = credentials.Certificate(json.loads(key_json))
        else:
            cred = credentials.Certificate("serviceAccountKey.json")
        
        firebase_admin.initialize_app(cred, {
            'databaseURL': os.environ.get("FIREBASE_DB_URL")
        })
    except Exception as e:
        console.print(f"[red]⚠️ Firebase Error: {e}[/red]")

class AJXFinalSupervisor:
    def __init__(self, subject_name):
        self.subject = subject_name.upper()
        # GitHub Actions usually collects artifacts here
        self.source_path = f"BACKUP/{self.subject}" 
        self.monitor_ref = db.reference(f'Monitoring/{self.subject}/Finalizer')

    def update_remote(self, status, message):
        try:
            self.monitor_ref.update({"status": status, "message": message, "timestamp": int(time.time())})
        except: pass

    # ==========================================
    # 🕵️♂️ CORE LOGIC: INTEGRITY CHECK (DSA)
    # ==========================================
    
    def verify_integrity(self):
        """
        Scans every single JSON file generated by Workers.
        Checks for:
        1. JSON Validity
        2. Global ID Collisions (CRITICAL)
        3. Generates Manifest for App
        """
        console.print("[yellow]🕵️♂️ Auditing Data Integrity...[/yellow]")
        
        seen_ids = set()
        collision_errors = []
        manifest = {}
        total_questions = 0
        file_count = 0

        # Recursive Walk (Unit -> Chapter -> Page.json)
        for root, dirs, files in os.walk(self.source_path):
            files = natsorted(files)
            
            for file in files:
                if not file.endswith(".json"): continue
                
                file_path = os.path.join(root, file)
                file_count += 1
                
                # Derive Structure from Path
                # Expected: BACKUP/UPSI_HISTORY/01_Ancient/01_Stone_Age/1.json
                rel_path = os.path.relpath(file_path, self.source_path)
                parts = rel_path.split(os.sep)
                
                if len(parts) >= 2:
                    unit = parts[-3] if len(parts) > 2 else "Uncategorized"
                    chapter = parts[-2]
                else:
                    unit = "Root"
                    chapter = "General"

                try:
                    with open(file_path, 'r', encoding='utf-8') as f:
                        data = json.load(f)
                        
                        # 1. Check Format
                        if not isinstance(data, list):
                            console.print(f"[red]❌ Invalid Format (Not List): {rel_path}[/red]")
                            continue

                        # 2. Check IDs
                        local_min_id = float('inf')
                        local_max_id = float('-inf')
                        
                        for item in data:
                            q_id = item.get('id')
                            if not q_id: continue
                            
                            # COLLISION DETECTOR (Set O(1))
                            if q_id in seen_ids:
                                collision_errors.append(f"ID {q_id} duplicated in {rel_path}")
                            else:
                                seen_ids.add(q_id)
                            
                            local_min_id = min(local_min_id, q_id)
                            local_max_id = max(local_max_id, q_id)
                        
                        # 3. Build Manifest Node
                        if unit not in manifest: manifest[unit] = {}
                        if chapter not in manifest[unit]: 
                            manifest[unit][chapter] = {"files": [], "total_q": 0}
                        
                        count = len(data)
                        total_questions += count
                        manifest[unit][chapter]["total_q"] += count
                        manifest[unit][chapter]["files"].append({
                            "file_name": file,
                            "count": count,
                            "id_range": f"{local_min_id} - {local_max_id}"
                        })
                        
                except Exception as e:
                    console.print(f"[red]❌ Corrupt File {rel_path}: {e}[/red]")

        # REPORTING
        if collision_errors:
            console.print(Panel(f"[bold red]💥 CRITICAL: {len(collision_errors)} ID COLLISIONS FOUND![/bold red]"))
            for err in collision_errors[:5]: console.print(f"[red]- {err}[/red]")
            return None # Stop Process
            
        return manifest, total_questions

    def upload_manifest(self, manifest):
        """Uploads the App-Friendly Manifest to Firebase"""
        console.print("[yellow]📤 Uploading Master Manifest...[/yellow]")
        ref = db.reference(f'Syllabus/{self.subject}/Manifest')
        ref.set(manifest)
        
        # Mark Config as LIVE
        db.reference(f'Syllabus/{self.subject}/Config').update({
            "status": "LIVE",
            "last_sync": int(time.time()),
            "total_questions": self.total_q_count
        })

    def run(self):
        console.print(Panel(f"[bold magenta]🏁 AJX SUPERVISOR: {self.subject}[/bold magenta]"))
        
        # Step 1: Verification
        result = self.verify_integrity()
        
        if result:
            manifest, total_q = result
            self.total_q_count = total_q
            
            # Step 2: Show Tree Summary
            tree = Tree(f"📁 {self.subject} ({total_q} Questions)")
            for unit, chapters in manifest.items():
                u_node = tree.add(f"[bold cyan]{unit}[/bold cyan]")
                for chap, meta in chapters.items():
                    u_node.add(f"[green]{chap}[/green] ({meta['total_q']} Qs)")
            console.print(tree)
            
            # Step 3: Finalize
            self.upload_manifest(manifest)
            self.update_remote("LIVE", "Sync Complete")
            console.print(Panel(f"[bold green]✅ SYSTEM LIVE! NO ERRORS FOUND.[/bold green]"))
            
        else:
            self.update_remote("ERROR", "ID Collisions Detected")
            console.print(Panel(f"[bold red]❌ SYNC ABORTED DUE TO ERRORS[/bold red]"))

if __name__ == "__main__":
    # Environment variable sets the subject
    subject = os.getenv("CURRENT_SUBJECT", "UPSI_HISTORY")
    if os.path.exists(f"BACKUP/{subject}"):
        AJXFinalSupervisor(subject).run()
    else:
        console.print(f"[red]❌ Backup folder for {subject} not found. Did Workers finish?[/red]")
